get http://localhost:1212
###
get http://localhost:1212/products
###
get http://localhost:1212/products/5df8060116caa659d0d65e1f
###
POST http://localhost:1212/products
Content-Type: application/json

{
    "name": "rich dad Poor dad",
    "price": 10000
}
###
delete http://localhost:1212/orders/123
###
POST http://localhost:1212/orders
Content-Type: application/json

{

}