get http://localhost:1212
###
get http://localhost:1212/products
###
get http://localhost:1212/products/5df8d32108e0067c1460b266
###
POST http://localhost:1212/products
Content-Type: application/json

{
    "name": "sweet jamaica",
    "price": 78000
}
###
put http://localhost:1212/products/5df8d32108e0067c1460b266
Content-Type: application/json

{
    "name": "jaja woman 2",
    "price": 4600
}
###
PATCH  http://localhost:1212/products/5df8d32108e0067c1460b266
Content-Type: application/json

{
    "name": "jaja woman 2.1"
}
###
delete http://localhost:1212/products/5df8d32108e0067c1460b266
###
POST http://localhost:1212/orders
Content-Type: application/json

{

}