get http://localhost:1212
###
get http://localhost:1212/products
###
get http://localhost:1212/products/5dfa64492ffc2582a4805d1e
###
POST http://localhost:1212/products
Content-Type: application/json

{
    "name": "sweet jamaica",
    "price": 78000
}
###
put http://localhost:1212/products/5dfa64492ffc2582a4805d1e
Content-Type: application/json

{
    "name": "sweet splits jamaica",
    "price": 100000
}
###
PATCH  http://localhost:1212/products/5dfa64492ffc2582a4805d1e
Content-Type: application/json

{
    "name": "juma man swett pupu"
}
###
delete http://localhost:1212/localhost:1212/products/5dfa64492ffc2582a4805d1e
###
POST http://localhost:1212/orders
Content-Type: application/json

{

}